#!/bin/bash
[ -n "$BASH_SOURCE" ] || { echo 1>&2 "source (.) this with Bash."; exit 2; }
(
    cd "$(dirname "$BASH_SOURCE")"
    [ -d venv ] || {
        python3 -m venv venv/python3-virtualenv
        . venv/python3-virtualenv/bin/activate
        pip install -r requirements.txt
    }
)
. "$(dirname "$BASH_SOURCE")/venv/python3-virtualenv/bin/activate"